name: Pull Request
description: Submit a new pull request linked to an issue
title: "PR: [TAG] Short description"
labels: []
body:
  - type: input
    id: pr_title
    attributes:
      label: PR Name
      description: Write a clear, descriptive title for your PR
      placeholder: "e.g. PR: [BUG] Fix navbar not loading"
    validations:
      required: true

  - type: input
    id: issue_reference
    attributes:
      label: Related Issue
      description: Link the related issue number or commit (e.g., Fixes #42, Related to abc1234)
      placeholder: "Fixes #42"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Briefly explain the changes made in this PR
      placeholder: "Summary of changes"
    validations:
      required: true

  - type: dropdown
    id: change_type
    attributes:
      label: Type of Change
      description: Select the type(s) of change
      multiple: true
      options:
        - Bug fix (BUG)
        - Documentation (DOC)
        - Performance improvement (PERF)
        - UI/UX improvement (UIX)
        - Sensitive info redaction (ISL)
        - Urgent fix/review (IRE)
        - Other
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: "Linked this PR to a valid issue"
          required: true
        - label: "Followed repo’s Issue & Redaction Rules"
          required: true
        - label: "Updated docs if needed"
          required: false
        - label: "Performed a quick self-review"
          required: false

  - type: markdown
    attributes:
      value: |
        📌 **Note**  
        - Every PR must connect to an issue reference (commit, PR, line, or feature ID).  
        - Use the correct tags (`BUG`, `DOC`, `ISL`, etc.).  
        - PRs without issue references may be **closed without review**.
