name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Add meta tags and maintenance script to index.html
      - name: Prepare index.html
        run: |
          INDEX="index.html"
          # Inject SEO and charset meta tags if missing
          if ! grep -q '<meta charset="UTF-8">' "$INDEX"; then
            sed -i '1i\<meta charset="UTF-8">\n<meta name="viewport" content="width=device-width, initial-scale=1.0">\n<meta name="description" content="My static website">' "$INDEX"
          fi
          # Inject maintenance.js loader if maintenanceMode is true
          if grep -q 'window.maintenanceMode = true' "js/maintenance.js"; then
            if ! grep -q '<script src="js/maintenance.js">' "$INDEX"; then
              sed -i '/<\/body>/i <script src="js/maintenance.js"></script>' "$INDEX"
            fi
          fi

      # 3. Setup GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 4. Upload only site files (exclude unnecessary folders)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: |
            index.html
            favicon.ico
            maintenance.html
            js/
            LICENSE.md
            static.yml

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
